
var movies={"movies":[
                     {"title": "Blue Streak", "year": 1999, "Starring": "Martin Lawrence, Luke Wilson", "Description": "Blue Streak is a 1999 American buddy cop comedy film directed by Les Mayfield and starring Martin Lawrence, Luke Wilson, Dave Chappelle, Peter Greene, Nicole Ari Parker and William Forsythe. The film was shot on location in California. The prime shooting spot was Sony Pictures Studios which is located in Culver City, California.", "HD":true, "genre":"comedy", "photo":"data/blue-streak.jpg","rating":4},
                     {"title": "Mrs. Doubtfire", "year": 1993, "Starring": "Robin Williams, Sally Field", "Description": "Mrs. Doubtfire is a 1993 American comedy film starring Robin Williams (who also served as co-producer) and Sally Field and based on the novel Alias Madame Doubtfire by Anne Fine. It was directed by Chris Columbus and distributed by 20th Century Fox. It won the Academy Award for Best Makeup.", "HD":false, "genre":"comedy", "photo":"data/doubt_fire.jpg","rating":5},
                     {"title": "Life of Pi", "year": 2012, "Starring": "Suraj Sharma, Irrfan Khan", "Description": "Life of Pi is a Canadian fantasy adventure novel by Yann Martel published in 2001. The protagonist, Piscine Molitor 'Pi' Patel, an Indian boy from Pondicherry, explores issues of spirituality and practicality from an early age. He survives 227 days after a shipwreck while stranded on a lifeboat in the Pacific Ocean with a Bengal tiger named Richard Parker.", "HD":true, "genre":"drama", "photo":"data/life_of_pi.jpg","rating":5},
                     {"title": "The Pacific", "year": 2010, "Starring": "James Badge Dale, Joseph Mazzello", "Description": "The Pacific is a 2010 television series produced by HBO, Seven Network Australia, Sky Movies, Playtone and DreamWorks that premiered in the United States on 14 March 2010.", "HD":true, "genre":"action", "photo":"data/pacific.jpg","rating":3},
                     {"title": "Rio", "year": 2011, "Starring": "Jesse Eisenberg, Leslie Mann", "Description": "Rio is a 2011 American 3D computer-animated musical adventure-comedy film produced by Blue Sky Studios and directed by Carlos Saldanha. The title refers to the Brazilian city of Rio de Janeiro, where the film is set. ", "HD":true, "genre":"action", "photo":"data/rio.jpg","rating":4},
                     {"title": "An Unfinished Life", "year": 2005, "Starring": "Robert Redford, Jennifer Lopez", "Description": "An Unfinished Life is a 2005 drama film directed by Swedish director Lasse Hallström, and based on the Mark Spragg novel of the same name. The film stars Robert Redford, Jennifer Lopez, and Morgan Freeman. ", "HD":false, "genre":"drama", "photo":"data/unfinished_life.jpg","rating":3},
                     {"title": "The Woman in Black", "year": 2012, "Starring": "Lu Corfield, Daniel Radcliffe", "Description": "England, 1941 With London in the midst of the blitz, two teachers evacuate a group of school children to the abandoned Eel Marsh House. Seeking safety from the bombs in the remote coastal location, the group instead find themselves facing an evil far more frightening when their arrival awakens the Woman in Black.", "HD":true, "genre":"horro", "photo":"data/woman_in_black.jpg","rating":5}
                     ]};
